{% set name = "amityping" %}
{% set version = "1.1.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/slac-lcls/{{ name }}/archive/{{ version }}.tar.gz
  sha256: e00e7102a53fa6ee343f018669f6b811d703a2da4728b497f80579bf89efbd3c

build:
  skip: True  # [win]
  noarch: python 
  number: 19
  script:
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - numpy
    - mypy_extensions

about:
  home: https://github.com/slac-lcls/amityping
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'Type hints for LCLS-II software'
  description: |
    provides typing hints to be shared between LCLS-II analysis packages.
  doc_url: https://github.com/slac-lcls/amityping
  dev_url: https://github.com/slac-lcls/amityping

extra:
  recipe-maintainers:
    - valmar
    - chrisvam
