image: continuumio/miniconda3

stages:
  - build

build_stage:
  before_script:
    - apt-get update
    - conda init bash
    - conda create -n conda_build conda-build conda-verify anaconda_client
    - conda activate conda_build
  script:
    - conda build recipe
  artifacts:
    paths:
    - conda-bld/linux-64
  only:
  - master
